# Created by trellis-cli v1.10.1
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  ineedthatcomic.com:
    site_hosts:
    - canonical: ineedthatcomic.com
      redirects:
      - www.ineedthatcomic.com
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
    xmlrpc:
      enabled: true
